language: groovy

jdk:
  - openjdk6
  - openjdk7

script:
  - ./gradlew clean assemble test uploadArchives
  # This will compile Android projects which needs Android SDK.
  # It makes tests so slow, so disables it.
  #- cd samples/consumer && ./gradlew -b gag.gradle
